### ISSUE TITLE
is it still maintained?

### ISSUE THREAD

**Issue by twojcik** [dvv/simple-geoip#1]
Hi I'm interesed in using that lib in my new project, but not sure if it's still maintained? I like simplicity of the lib and that it doesn't depend on any c lib ? Or you would advise to use https://github.com/kuno/GeoIP ? Is your's lib still the fastest ?:)

**Comment by dvv** [comment]
Am deeply sorry for the delay, Tadeusz!

AFAICS, there's nothing to maintain here. To stay tuned to the recent data, just clone afresh and run ./install -- this will fetch the latest geoip bases and will prepare the cache.

AFAIK, kuno's adopted my technique of seeking for records, so I believe his lib should be quick enough.

Please, feel free to feedback/blame/request for features.

Best regards,
--Vladimir

**Comment by twojcik** [comment]
Thanks for the update Vladimir. I've checked kuno's module and his approach is to use c library provided by maximind underneath. I found you approach very interesting as you basically written parsing  maximind database structure in coffeescript and load it into memory. I've made few benchmarks and your module was the fastest one (about 10-20% on average), but I found that long/lat coordinates were rounded up somehow.
BTW. Did you move all your development effort to lua? How it compares to node? I'm starting new project and was considering luvit, but seems little to young/unstable now.

**Comment by dvv** [comment]
I do truncate at https://github.com/dvv/simple-geoip/blob/master/lib/index.js#L129 . Have forgotten the reasons, frankly :)

Node's entered inertial, extensive development phase. Decisions are made and settled.
Luvit is a hot point. I like to participate in something new, really.
Luvit's now under refactoring, there are some edge cases, but otherwise it's quite usable -- please, refer to my dvv/luvit-\* projects. Luvit's using circa 2Mb of memory for even consuming tasks, and is faster about 2-3 times over node (measured by serving static files, e.g.)

Come join us at #luvit to have it mature :)

**Comment by twojcik** [comment]
Thank Vladimir !
I think I'll take a closer look at luvit in near future:)
